# command line: try_get_data.py

base_lr: 0.1
batch_size: 1
config: config.yaml
device:
- 1
eval_interval: 5
feeder: feeders.feeder_ntu_zhr_2.Feeder
ignore_weights: []
log_interval: 100
lr_decay_rate: 0.1
model: model.ctrgcn_zhr.Model
model_args:
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 60
  num_person: 2
  num_point: 25
model_saved_name: ''
nesterov: true
num_epoch: 10
num_worker: 32
optimizer: SGD
phase: train
print_log: true
save_epoch: 30
save_interval: 1
save_score: true
seed: 1
show_topk:
- 1
- 5
start_epoch: 1
step:
- 35
- 55
test_batch_size: 64
test_feeder_args:
  bone: false
  data_path: data/ntu/NTU60_zhr2_add_spin.npz
  debug: false
  p_interval:
  - 0.95
  split: test
  vel: false
  window_size: 64
train_feeder_args:
  bone: false
  data_path: data/ntu/NTU60_zhr2_add_spin.npz
  debug: false
  normalization: false
  p_interval:
  - 0.5
  - 1
  random_choose: false
  random_move: false
  random_rot: true
  random_shift: false
  split: train
  vel: false
  window_size: 64
warm_up_epoch: 5
weight_decay: 0.0004
weights: CTR_ZHR/runs-main_zhr_2-28475.pt
work_dir: work_dir_train
